version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=zacharym
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=state-restaurant-web-app-db-1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
