export const MAX_OUTBOUND_SHIPMENT_IMAGES = 10;
export const MAX_OUTBOUND_SHIPMENT_IMAGE_BYTES = 5 * 1024 * 1024;
export const MAX_OUTBOUND_SHIPMENT_UPLOAD_BYTES = 4 * 1024 * 1024;
export const OUTBOUND_SHIPMENT_RETENTION_MONTHS = 6;
export const OUTBOUND_IMAGE_MAX_DIMENSION = 1600;
export const OUTBOUND_IMAGE_JPEG_QUALITY = 0.72;
